python3 main.py \
    --output_dir “test-vqa” \
    --logging_steps 400 \
    --eval_steps 400 \
    --save_steps 400 \
    --max_train_samples 2000 \
    --max_eval_samples_per_lang 200 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 512 \
